version: '3.1'

services:
  # backend:
  #   image: node:21.4.0
  #   command: sh -c "cd ./backend && npm run start:dev"
  #   working_dir: /monorepo
  #   volumes:
  #     - ./:/monorepo
  #   ports:
  #     - 3000:3000

  db:
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: compta

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 9090:8080