module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './../shared-components/src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    colors: {
      gold: '#C4AB61',
      'gold-dimmed': '#8C7D50',
      'gold-gloomy': '#9C9A66',
      'light-gold': '#F6ECCD',
      silver: '#9FA1A6',
      'silver-dimmed': '#4A4A49',
      green: '#6C9D54',
      'light-green': '#E8FADD',
      'bright-green': '#70B051',
      'green-dimmed': '#009000',
      black: '#000000',
      'fake-black': '#222730',
      'fake-white': '#F2F2F2',
      white: '#FFFFFF',
      'white-dimmed': 'rgba(255, 255, 255, 0.15)',
      'dark-gray': '#3B3E46',
      'dark-gray-dimmed': 'rgba(59, 62, 70, 0.6)',
      gray: '#828693',
      'light-gray': '#DEDEDE',
      red: '#C26170',
      'light-red': '#F9DBDF',
      'dark-red': '#C26170',
      'darker-red': '#97303B',
      'bright-red': '#BD323A',
      'fade-black': '#31353c',
      'fade-white': '#FAFAFA',
      transparent: 'rgba(0, 0, 0, 0)',
      orange: '#EEA334',
      'orange-dimmed': '#C69369',
    },
    fontFamily: {
      sans: ['Source sans pro', 'sans-serif'],
      roboto: ['Roboto', 'sans-serif'],
    },
    borderRadius: {
      sm: '3px',
      md: '5px',
      full: '9999px',
    },
    boxShadow: {
      dark: '0px 8px 20px rgba(0, 0, 0, 0.3)',
      light: '0px 8px 15px rgba(0, 0, 0, 0.08)',
    },
    fontSize: {
      '4xl': ['2.25rem', '2.5rem'],
      '3xl': ['1.875rem', '2.25rem'],
      '2xl': ['1.5rem', '2rem'],
      xl: ['1.25rem', '1.75rem'],
      lg: '20px',
      md: '15px',
      sm: '13px',
    },
    text: {
      '2xl': '30px',
      lg: '20px',
      md: '15px',
      sm: '13px',
    },
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      '2lg': '1130px',
      xl: '1280px',
      '2xl': '1536px',
      '3xl': '1800px',
    },
    animation: {
      fadeIn: 'fadeIn 0.1s ease-in',
      fadeOut: 'fadeOut 1s ease-out',
      spin: 'spin 1s linear infinite',
    },
    keyframes: (theme) => ({
      fadeIn: {
        '0%': { opacity: theme('opacity.0') },
        '100%': { opacity: theme('opacity.100') },
      },
      fadeOut: {
        '0%': { opacity: theme('opacity.100') },
        '100%': { opacity: theme('opacity.0') },
      },
    }),
  },
  plugins: [require('@tailwindcss/typography')],
};
